### ISSUE TITLE
Something wrong with inference.py, the output file can't be played.

### ISSUE THREAD

**Issue by cwh0118** [slSeanWU/jazz_transformer#2]
As I follow the instructions to compose music

I got this log output:

Start model inference...
2020-08-05 05:55:32.732437: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-05 05:55:33.762416: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
failed iterations: 1
failed iterations: 1
failed iterations: 2
failed iterations: 3
failed iterations: 4
failed iterations: 5
failed iterations: 6
failed iterations: 7
failed iterations: 8
failed iterations: 9
failed iterations: 10
failed iterations: 1
failed iterations: 1
failed iterations: 1
generated 6460 events
First 20 events: ['Part-Start_I', 'Rep-Start_1', 'Bar', 'Position_0/64', 'Tempo-Class_0', 'Tempo_67.50', 'Position_16/64', 'Tempo-Class_0', 'Tempo_65.00', 'Position_32/64', 'Tempo-Class_0', 'Tempo_67.50', 'Position_48/64', 'Tempo-Class_0', 'Tempo_62.50', 'Position_55/64', 'Phrase', 'MLU-Type_lick', 'MLU-Subtype_lick-general', 'Backref-Referred']

now converting events to MIDI: ./output/test.mid ...

It did generate midi file in output dir, but the file can't be played in normal player. It seems like the writing file stage makes something wrong ...

**Comment by slSeanWU** [comment]
May I check the generated MIDI file? Also, what MIDI player do you use?

**Comment by cwh0118** [comment]
Hi, It's a great work! Thanks for sharing the project.

Here is how I do:
!python inference.py --n_bars 64 --struct_csv ./output/test.csv ./output/test.mid

And Here is the log output:
![image](https://user-images.githubusercontent.com/55170770/89386751-15121800-d734-11ea-9116-4071654692cb.png)


The players I use are:
Windows media player
![image (1)](https://user-images.githubusercontent.com/55170770/89386760-1b07f900-d734-11ea-87de-ea686ef73332.png)
MuseScore 3
![image (2)](https://user-images.githubusercontent.com/55170770/89386766-1d6a5300-d734-11ea-9e47-d864052fe44b.png)


The midi file & csv file are in the attachment
[test.zip](https://github.com/slSeanWU/jazz_transformer/files/5026950/test.zip)

**Comment by slSeanWU** [comment]
Hi cwh0118,

Sorry, but I don't see any attachment on my side.

**Comment by cwh0118** [comment]
Sor about that, I replied through E-mail last comment.
I edited the reply. 
Now, you can check that again. Big THX

**Comment by slSeanWU** [comment]
Hi, it's a bug ... XD.

It arises from the output file path of the ``generated event sequence``.  I (mistakenly) assumed the extension of the MIDI to be `.midi` , thus when `.mid` is used instead, the MIDI content will be over-written by the ``generated event sequence``.

I've fixed this. Now, after inference, you should see the MIDI file (ending with `.mid` or `.midi`, depending on the given argument); plus, a `.csv` file that shares the same name with the MIDI and contains the event tokens generated by Jazz Transformer. You may give it a try, hope it works now!

Thanks for spotting this bug!!

**Comment by cwh0118** [comment]
It works! 👍 
THX again.
