### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by asigalov61** [slSeanWU/jazz_transformer#3]
Hey guys,

Thank you for sharing your work. Looks very nice and promising.

I have a question: Is it possible to use your code/can you provide code to train on my own MIDI dataset. It seems that you are using proprietary format of the Jazz dataset so I can't try it on my own to evaluate your work and results.

I will really appreciate your help here.

Thank you.

**Comment by slSeanWU** [comment]
Hello,

If you would like to train on MIDIs, I recommend that you take a look at my colleague's repository:
https://github.com/YatingMusic/remi

It provides full functionalities for MIDI-to-event conversion, and model training/inference (also Transformer-XL).
Thanks! Happy training!

**Comment by asigalov61** [comment]
Thank you very much for your suggestion but I already tried REMI repo/code and it does not have a code to train from scratch + the dev (your colleague?) told me that they do not plan to release training from scratch code so REMI repo is not very helpful/useful to me at the moment.

But still, great work on Jazz Transformer and on all of your other repos/projects. Looks very promising and interesting. I wish you guys luck.
